INSERT INTO DUENO (DOCUMENTO, NOMBRE, ESTADO) VALUES('123456789', 'Ivan 1', 'Activo');
INSERT INTO DUENO (DOCUMENTO, NOMBRE, ESTADO) VALUES('123456789', 'Ivan 2', 'Activo');

INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, CIUDAD, ESTADO, VALOR) VALUES
('Restaurante 1', 'CALLE 21', 'bogota', 'Activo', 100.0);
INSERT INTO RESTAURANTE (NOMBRE, DIRECCION, CIUDAD, ESTADO, VALOR) VALUES
('Restaurante 2', 'CALLE 34-12', 'bogota', 'Activo', 100.0);


INSERT INTO RESTAURANTE_DUENO (FK_RESTAURANTE, FK_DUENO, COMISION) VALUES
(1, 1, 0.15);

INSERT INTO RESTAURANTE_DUENO (FK_RESTAURANTE, FK_DUENO, COMISION) VALUES
(1, 1, 0.20);

INSERT INTO EMPLEADO (DOCUMENTO, NOMBRE, SUELDO, ESTADO, FK_RESTAURANTE) VALUES
('123456789', 'Andres 1', 20000, 'Activo', 1);
INSERT INTO EMPLEADO (DOCUMENTO, NOMBRE, SUELDO, ESTADO, FK_RESTAURANTE) VALUES
('123456789', 'Andres 2', 20000, 'Activo', 1);
INSERT INTO EMPLEADO (DOCUMENTO, NOMBRE, SUELDO, ESTADO, FK_RESTAURANTE) VALUES
('123452789', 'Andres 3', 10000, 'Activo', 2);